### ISSUE TITLE
Unhandled api error

### ISSUE THREAD

**Issue by misaelnieto** [paypal/Checkout-Python-SDK#11]
User pays using the javascript library `https://www.paypal.com/sdk/js`. When the payment succeeds, the browser POSTs the paypal's `auth_id` (along to a custom `lfsd_uuid`) to a django backend, which is using paypal-checkout-serversdk==1.0.0. The code is this:

```python
    credentials = {
        'client_id': django_settings.LFSD_PAYPAL_CLIENT_ID,
        'client_secret': django_settings.LFSD_PAYPAL_CLIENT_SECRET
    }
    pp_env = pp_debug and SandboxEnvironment(**credentials) or LiveEnvironment(**credentials)
    pp_client = PayPalHttpClient(pp_env)
    lfsd_uuid = request.POST['lfsd_uuid']

    reqi = OrdersGetRequest(request.POST['auth_id'])
    pp_response = pp_client.execute(reqi)
```
`pp_client.execute()` fails with the following error:

```json
{
  "ack": "error",
  "message": "Unhandled api error",
  "meta": {
    "calc": "6db081e02a363",
    "rlog": "3seNgqjNj3X4wqjpEL6lJfYh1p3bhBc1PDIZY0cJqrqdycXBwgHQt4ub2euJdVRiN4X908NWEAk5d6ZlRTRNJQ_169505015aa"
  },
  "server": "Fkq7UbjhG0RsP5tTJ0k2_fBi5pFf9oOvQLixSWw57ogsFGiUBM2hYl3WhxG44Kf_ihdB-i1H0-0zza4HVa6krHxMiBTyKEVYIq6kJUk9kAuzJipZC-6Uc_QulX9r0PDSAA5M8sccWMyaJQZoO1dpsjsXYySrlqhCJpEpGToTuvrhSDaNwNCc3HXHV9WIHdDtS-L0-NHrRe7NMyMQ2Ox00rlxZrOGMd4KIvhPeKj3yt69wEv4SRcrdPCE_04DdcRN"
}
```
The same code succeeds when using the sandbox.

What I'm doing  wrong?

**Comment by rajarampadmanathan** [comment]
HI @misaelnieto - From the error response it looks like the capture call from https://www.paypal.com/sdk/js to paypal server is failing. 

@bluepnume can you please check this (it looks like client id is missing during the capture call) ?

**Comment by rajarampadmanathan** [comment]
HI @misaelnieto - Can you please provide an latest debug id?

**Comment by ganeshramc** [comment]
Hi @misaelnieto, following up to see if you could provide a latest debug id

**Comment by ganeshramc** [comment]
Hey @misaelnieto, we are going to close this issue in 7 days unless you have any more updates. Thanks!
