### ISSUE TITLE
SDK is still beta and should not be used in prod, but advertised in the offical paypal doc!

### ISSUE THREAD

**Issue by sposs** [paypal/Checkout-Python-SDK#12]
In the official paypal developers docs, this SDK is the recommended choice to use with Python when using the new checkout frontend API (sdk/js). Is the official documentation of Paypal wrong? I really hope this github's repo doc is incorrect... Otherwise, please advise what backend library should be used in prod.

Thanks!

**Comment by rajarampadmanathan** [comment]
Hi @sposs - Can you please provide me the developer docs link where you see this recommendation?

**Comment by sposs** [comment]
https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/

**Comment by sposs** [comment]
In the bottom of the page, there is a link pointing to this repo.

**Comment by rajarampadmanathan** [comment]
Got the issue. README.md has an incorrect note. This SDK is production ready one.
 Updated the README.md to remove beta related description.

**Comment by rajarampadmanathan** [comment]
@sposs - Can i mark this as resolved? Please let me know if you have further queries/issues.

**Comment by sposs** [comment]
Yes, it's clear now.
