### ISSUE TITLE
object_to_json error

### ISSUE THREAD

**Issue by danil-smirnov** [paypal/Checkout-Python-SDK#15]
Hi,

When I try to convert OrdersGetRequest response result to json-serializable as per [documentation](https://github.com/paypal/Checkout-Python-SDK/blob/develop/sample/get_order.py#L22), I get the following error:

```
File "/var/task/chalicelib/paypal.py", line 57, in get_order
return response, self.object_to_json(response.result)
File "/var/task/chalicelib/paypal.py", line 33, in object_to_json
result[key] = self.array_to_json_array(value) if isinstance(value, list) else\
File "/var/task/chalicelib/paypal.py", line 41, in array_to_json_array
result.append(self.object_to_json(item) if not self.is_primittive(item) \
File "/var/task/chalicelib/paypal.py", line 46, in is_primittive
return isinstance(data, str) or isinstance(data, unicode) or isinstance(data, int)
NameError: name 'unicode' is not defined
```

**Comment by rajarampadmanathan** [comment]
Hi @danil-smirnov - I tried to replicate this but not able to replciate. This is not happening with regular transactions.  Can you please provide more info on this issue? Like Transaction id, PayPal debug Id, is this happening only with failure response or with success responses as well, etc.,

Thanks.

**Comment by danil-smirnov** [comment]
Hi @rajarampadmanathan 
I'm using Sandbox and I'm getting this on success only (as I don't reach the object_to_json function in my code otherwise).
I've just created a transaction with id 7CF790464S213390V - I hope you can check.
I don't know how to find PayPal debug Id, sorry
p.s. I'm using Python 3.6 and paypal-checkout-serversdk 1.0.0

**Comment by danil-smirnov** [comment]
Any news @rajarampadmanathan ?

**Comment by pengpeng11** [comment]
@danil-smirnov could you please provide a PayPal debug id for the transaction in sandbox? it will help us locating the root cause very quick.

**Comment by danil-smirnov** [comment]
@pengpeng11 Where can I find that debug id?

**Comment by pengpeng11** [comment]
@danil-smirnov  it is in the header of response.

**Comment by danil-smirnov** [comment]
@pengpeng11 
Order ID: 7SG26671TY743993Y
Debug ID: f2d86b5b47426

**Comment by danil-smirnov** [comment]
Any news @pengpeng11 ?

**Comment by pengpeng11** [comment]
@danil-smirnov 
are you using Python3?
Python 3 renamed the `unicode` type to `str`
Could you please try:
1, use Python 2 instead.
or 
2, remove the `or isinstance(data, unicode)` condition from `is_primittive` method in sample/paypal_client.py

**Comment by danil-smirnov** [comment]
@pengpeng11 Yes I'm using Python 3 and have no plans to degrade my code to Python 2.
Option 2 works for me - the issue is resolved, thank you very much!
