### ISSUE TITLE
Return Verified Status field

### ISSUE THREAD

**Issue by boosth** [paypal/Checkout-Python-SDK#16]
Can you please add the payers "verified" status to the details returned by OrdersGetRequest() ?

I have a digital good that is not covered by Seller Protection and currently I have to manually check every transaction to see if the account is verified or not as part of my security measures to minimize the risk of a chargeback from an unauthorized payment using a stolen card. It would be much easier for me if I could retrieve that field from the orders api.

**Comment by rajarampadmanathan** [comment]
Thanks @boosth for contacting us. 
@rsdighe76 -  Can you please check this? Currently [Payer object ](https://developer.paypal.com/docs/api/orders/v2/#definition-payer) doesn't have the status field.

**Comment by rsdighe76** [comment]
Can you elaborate a bit on your integration pattern/workflow ? do you use intent="authorize" or "capture" ? - for e.g. do you do Create Order, Authorize Order - then check your PayPal Seller account online to see if payer/buyer is verified and then capture or void the authorization? is that your workflow.

**Comment by ganeshramc** [comment]
Hi @boosth following up to see if you have an update to @rsdighe76 question

**Comment by ganeshramc** [comment]
Hey @boosth, we are going to be closing this issue in 7 days unless you need more clarification. Thanks :)
