### ISSUE TITLE
disable guest checkout with personal account

### ISSUE THREAD

**Issue by boosth** [paypal/Checkout-Python-SDK#17]
I have a business account and a personal account. I can disable guest checkout in my business account and buyers are forced to create a new account or login to an existing account when they make an order.

If I switch to my personal account which does not have guest checkout enabled because that variable is not available to personal accounts I see that buyers are able to make a guest checkout. 

According to paypal support guest checkout is not available for Personal accounts so can you please confirm if this is a bug of if the Support people are misinformed.

I want to disable guest checkout while using my Personal account as the seller. I can disable guest checkout wihen using a business account as a seller but it does not work for Personal accounts as sellers.

![screenshot-pp2](https://user-images.githubusercontent.com/1000775/57971812-a82e2900-799b-11e9-9880-d0e365567588.png)

BTW, the AI bot for the smc is infuriating. It consistently gives the wrong response.

**Comment by rajarampadmanathan** [comment]
@rsdighe76  - Can you please help with the above query?

**Comment by ganeshramc** [comment]
Hi @boosth. This isn't an SDK problem. I'm sure you integrated it properly. We are talking to internal teams to see if they have any possible causes/solutions. Will update you soon. Thanks!

**Comment by tctrini** [comment]
Hello @boosth ...   Like may other Selling Preferences PayPal offer the “My Selling tool” option (PayPal account optional -> Off) in the paypal.com PROFILE ONLY for Business A/Cs.  Unfortunately we do not offer this capability to casual sellers who have Personal A/Cs.  That say; in case you need this capability, you can upgrade the A/C to a business A/C from your profile page.

On your below comment; can you please point me to the same.  Seems like an outdated statement which we will get it rectified.
"According to paypal support guest checkout is not available for Personal accounts so can you please confirm if this is a bug of if the Support people are misinformed."

**Comment by Jaytea26896420** [comment]
Need some money sent to here    https://www.paypal.me/JCuthbertson266 it didn't work last time

**Comment by Jaytea26896420** [comment]
Please an thank you

**Comment by rsdighe76** [comment]
Closing issue considering there is no further update.
