### ISSUE TITLE
Add a note about how to install the PyPi release

### ISSUE THREAD

**Issue by NyanKiyoshi** [paypal/Checkout-Python-SDK#18]
Hi!

~~I did not find any information about using the SDK as a python dependency. What about releasing it into PyPi as `paypalcheckoutsdk`?~~

We probably could add the PyPi information into the README: `pip install paypal-checkout-serversdk`. It's not straightforward to install it (especially as it is telling us that "we might" want to fork it indirectly, to use it).

Cheers.

**Comment by ganeshramc** [comment]
Hey @NyanKiyoshi, thanks for the suggestion! It's mentioned at https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/#install-the-sdk
how to install the python sdk. In the readme we have a link `Please refer to the PayPal Checkout Integration Guide for more information. Also refer to Setup your SDK for additional information about setting up the SDK's.` which mentions how to setup the SDK. 
Thanks again :)

**Comment by christianbos** [comment]
why dont add this simple thing in the readme file?

**Comment by ganeshramc** [comment]
@christianbos it's on readme file as part of the intro!
