### ISSUE TITLE
Payer Phone Number

### ISSUE THREAD

**Issue by nuno-findster** [paypal/Checkout-Python-SDK#20]
I'm migrating our integration with Paypal (from API v1 to API v2) and after creating successfully an Order and respective Capture, your response never has the Payer "phone" field... 
(I've tried "OrdersCaptureRequest" and later "OrdersGetRequest" methods)

**Comment by bernard-56** [comment]
Hello,

I just migrated to V2 and I have the same problem. Have you disseminated the solution?
Thank you for your help

**Comment by ganeshramc** [comment]
Hi @bernard-56 and @nuno-findster, orders v2 api does not send payer phone number. We have changed this feature in orders v2 to allow more control over user's personal information. To request for that please contact customer care as this is an setting per merchant account to allow sending phone number.

**Comment by bernard-56** [comment]
Hello

Thank you for your reply. However, in the working interface, I activated the merchant phone number option. What else should i do?

**Comment by ganeshramc** [comment]
I don't believe merchant phone number and payer phone number are the same. merchant phone number would be yours and the payer phone number would be your customer's.

**Comment by bernard-56** [comment]
In the interface of the Merchant site, it is possible to define the mandatory parameters requested from the customer

**Comment by bernard-56** [comment]
Ok thank you. I will make requests directly via CURL. I should get the phone number.
I hope !!!

**Comment by GabrieleCicconetti** [comment]
@bernard-56 Did you solve this? i'm having the same problem
