### ISSUE TITLE
An error introduced by upgrade to 1.0.1 version

### ISSUE THREAD

**Issue by danil-smirnov** [paypal/Checkout-Python-SDK#23]
Hi,

I've just upgraded my Paypal backend code to version 1.0.1 and it stopped to work with error:

```
retention.live - DEBUG - Retrieving data from Paypal...
retention.live - ERROR - Caught exception for <function token at 0x7f9d0a45d268>
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 199, in token
    if paypal_check_order(order_id, amount_check):
  File "/var/task/app.py", line 785, in paypal_check_order
    order, order_json = GetOrder().get_order(order_id)
  File "/var/task/chalicelib/paypal.py", line 59, in get_order
    return response, self.object_to_json(response.result)
  File "/var/task/chalicelib/paypal.py", line 36, in object_to_json
    self.object_to_json(value) if not self.is_primittive(value) else\
  File "/var/task/chalicelib/paypal.py", line 30, in object_to_json
    itr = json_data.__dict__.items()
AttributeError: 'dict' object has no attribute '__dict__'
```

I'm using the code from the [sample](https://github.com/paypal/Checkout-Python-SDK/blob/develop/sample/paypal_client.py) with the one change discussed [here](https://github.com/paypal/Checkout-Python-SDK/issues/15#issuecomment-488788656) which is required for Python 3.6 runtime.

Could you help please?

**Comment by tiffanyrzhou** [comment]
Hello @danil-smirnov. Thanks for reaching out. I am looking into the problem right now. The primary change from the update is the usage of paypalhttp instead of braintreehttp. The problem may be a result of this replacement. I will update , with any additional information.
Thanks for your patience.

**Comment by tiffanyrzhou** [comment]
Hello @danil-smirnov. It appears that response.result contains a dict named "_dict" that is causing this error. Please try to add `or key.startswith("_")` to line 33 of samples/paypal_client.py. 
Thanks!

**Comment by danil-smirnov** [comment]
Hi @tiffanyrzhou
Thank you very much - the fix has resolved the issue.
While everything seems okay now, I personally would use "__" everywhere rather than multiple checks...
Closing the issue.
