### ISSUE TITLE
AttributeError: 'dict' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by dmalis** [paypal/Checkout-Python-SDK#24]
I'm getting and error with 1.0.1 (below) whereas there was none with 1.0.0

> File ".....gateways/paypal_express.py", line 49, in capture
        pp_order = pp_client.capture_order(order_id=order.payment_external_id)
      File "/Users/damjan/development/ecomm/src/libs/paypal.py", line 38, in capture_order
        return PayPalOrder(self.client.execute(request))
      File "/Users/damjan/development/ecomm/src/libs/paypal.py", line 79, in __init__
        self.result = DottedCollection.factory(PayPalClient.object_to_json(response.result))
      File "/Users/damjan/development/ecomm/src/libs/paypal.py", line 60, in object_to_json
        result[key] = PayPalClient.array_to_json_array(value) if isinstance(value, list) else PayPalClient.object_to_json(value) if not PayPalClient.is_primittive(value) else value
      File "/Users/damjan/development/ecomm/src/libs/paypal.py", line 60, in object_to_json
        result[key] = PayPalClient.array_to_json_array(value) if isinstance(value, list) else PayPalClient.object_to_json(value) if not PayPalClient.is_primittive(value) else value
      File "/Users/damjan/development/ecomm/src/libs/paypal.py", line 53, in object_to_json
        itr = json_data.__dict__.iteritems()
    AttributeError: 'dict' object has no attribute '__dict__'

**Comment by tiffanyrzhou** [comment]
Hello @dmalis this seems like a similar situation to https://github.com/paypal/Checkout-Python-SDK/issues/23 .  Please let me know if this helps.

**Comment by dmalis** [comment]
👍it fixed the issue. Could be useful to future developers, if you update the sample.

Thank you.

**Comment by jonathan-daniel** [comment]
why is the documentation so bad

**Comment by tiffanyrzhou** [comment]
Thank you for the feedback. We have updated our samples.
