### ISSUE TITLE
v2 library does not support recurring payments?

### ISSUE THREAD

**Issue by richmondu** [paypal/Checkout-Python-SDK#25]
This v2 library does not seem to support subscriptions/recurring payments, like the billing_plans and billing_agreements in v1 library below. https://github.com/paypal/PayPal-Python-SDK/tree/master/samples/subscription

Please provide documentation and extensive examples like in v1. It seems like this v2 library is worse than the v1. :(

**Comment by richmondu** [comment]
Is this library actively being improved? 
Is it advisable to use this library or the Braintree library instead?

**Comment by jonathan-daniel** [comment]
I don't know what's going on either, this API is such a mess

**Comment by saranglakare** [comment]
Looks like PayPal does not care about developers. I expected a simple integration and this is a mess. Have to write all code ourselves :(

**Comment by richmondu** [comment]
I've investigated using Braintree library and it seems like its the way to go. 
- supports Paypal payment and other payment methods including Apple Pay, Google Pay, etc, thus making your web/mobile payment system more robust
- for recurring payments feature, it supports seating plans, provisioning for discounts/addons, dashboard metrics, etc
- web app console is far better and more useful compared to Paypal.

**Comment by rsdighe76** [comment]
this SDK is not a replacement for PayPal-Python-SDK and it only supports features available as part of v2/checkout/orders and v2/payments.

**Comment by saranglakare** [comment]
Really? Go to site and you will see that PayPal-Python-SDK is deprecated! Do you really expect us to use deprecated stuff in production,  that too for financial stuff?

![Screen Shot 2020-06-16 at 12 19 51 PM](https://user-images.githubusercontent.com/4996891/84740956-ed23f500-afcb-11ea-8bab-c1e3626d0388.png)

I think PayPal is really clueless about what devs need - a simple and straight-forward integration.

**Comment by richmondu** [comment]
We gave up on using Paypal library. We’re now using Braintree library. Braintree is more simple and straightforward. It is also more developer-friendly. Check it out.

**Comment by saranglakare** [comment]
Thanks. Braintree is not available in India. Also, on their landing page, it is not clear at all who they are, how much do they charge, etc. It looks more like a developer site and does not give me comfort. I would rather integrate each payment gateway once and get done with it.
