### ISSUE TITLE
split payments

### ISSUE THREAD

**Issue by jonathan-daniel** [paypal/Checkout-Python-SDK#27]
is there a way to have an order with multiple receivers like in the old API?

**Comment by jonathan-daniel** [comment]
considering getting access to Payouts or Marketplace API's is impossible this feature is very important

**Comment by jonathan-daniel** [comment]
Of course no one answers

**Comment by jonathan-daniel** [comment]
Its like talking into the void

**Comment by jonathan-daniel** [comment]
whether you call Paypal directly, post a question on the forum, or open in issue on github, Paypal no care

**Comment by jonathan-daniel** [comment]
I guess the future is really in crypto currencies, I can send to as many people as I want

**Comment by rsdighe76** [comment]
Access to Marketplace features is vetted - the team here cannot influence who it is made available to. 

Could you clarify which API do you mean when you say Old API?
