### ISSUE TITLE
Transaction Search API

### ISSUE THREAD

**Issue by m0bi5** [paypal/Checkout-Python-SDK#29]
I have been searching the official PayPal repositories for a python SDK for the transaction search API - https://developer.paypal.com/docs/api/transaction-search/v1/.

Is there no such Python SDK available? Also the documentation says third party access is possible using the API but provides no information on how to do so. Can anybody help as to how to go about running transaction search API for a third party?

**Comment by rsdighe76** [comment]
This use case is not solved for by this particular SDK. I don't believe the team has an SDK yet. I will pass on the request to the team to think of it for their roadmap.
